; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\tdrol\documents\visual studio 2010\Projects\analizator\analizator-bd-opencl\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUgwiloUwlxfnvmghUerhfzoLhgfwrlLCABAUkilqvxghUzmzorazgliUzmzorazgliRywRlkvmxoUivovzhvUhgwzucOlyq@
___@@_PchSym_@00@UfhvihUgwiloUwlxfnvmghUerhfzoLhgfwrlLCABAUkilqvxghUzmzorazgliUzmzorazgliRywRlkvmxoUivovzhvUhgwzucOlyq@ DD 01H DUP (?)
END
