; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\tdrol\documents\visual studio 2010\Projects\analizator\analizator-bd-opencl\cl_encrypt_test.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?test_data@@3PAUEncrypt_Data@@A			; test_data
_DATA	SEGMENT
_test_data_size DD 06H
	ORG $+4
?test_data@@3PAUEncrypt_Data@@A DD 020H			; test_data
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DB	0dcH
	DB	095H
	DB	0c0H
	DB	078H
	DB	0a2H
	DB	040H
	DB	089H
	DB	089H
	DB	0adH
	DB	048H
	DB	0a2H
	DB	014H
	DB	092H
	DB	084H
	DB	020H
	DB	087H
	DD	020H
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DB	04bH
	DB	0f8H
	DB	05fH
	DB	01bH
	DB	05dH
	DB	054H
	DB	0adH
	DB	0bcH
	DB	030H
	DB	07bH
	DB	0aH
	DB	04H
	DB	083H
	DB	089H
	DB	0adH
	DB	0cbH
	DD	020H
	DB	00H
	DB	01H
	DB	02H
	DB	03H
	DB	04H
	DB	05H
	DB	06H
	DB	07H
	DB	08H
	DB	09H
	DB	0aH
	DB	0bH
	DB	0cH
	DB	0dH
	DB	0eH
	DB	0fH
	DB	010H
	DB	011H
	DB	012H
	DB	013H
	DB	014H
	DB	015H
	DB	016H
	DB	017H
	DB	018H
	DB	019H
	DB	01aH
	DB	01bH
	DB	01cH
	DB	01dH
	DB	01eH
	DB	01fH
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DB	0f2H
	DB	090H
	DB	00H
	DB	0b6H
	DB	02aH
	DB	049H
	DB	09fH
	DB	0d0H
	DB	0a9H
	DB	0f3H
	DB	09aH
	DB	06aH
	DB	0ddH
	DB	02eH
	DB	077H
	DB	080H
	DD	020H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	01H
	DB	02H
	DB	03H
	DB	04H
	DB	05H
	DB	06H
	DB	07H
	DB	08H
	DB	09H
	DB	0aH
	DB	0bH
	DB	0cH
	DB	0dH
	DB	0eH
	DB	0fH
	DB	010H
	DB	011H
	DB	012H
	DB	013H
	DB	014H
	DB	015H
	DB	016H
	DB	017H
	DB	018H
	DB	019H
	DB	01aH
	DB	01bH
	DB	01cH
	DB	01dH
	DB	01eH
	DB	01fH
	DB	020H
	DB	021H
	DB	022H
	DB	023H
	DB	024H
	DB	025H
	DB	026H
	DB	027H
	DB	028H
	DB	029H
	DB	02aH
	DB	02bH
	DB	02cH
	DB	02dH
	DB	02eH
	DB	02fH
	DB	030H
	DB	031H
	DB	032H
	DB	033H
	DB	034H
	DB	035H
	DB	036H
	DB	037H
	DB	038H
	DB	039H
	DB	03aH
	DB	03bH
	DB	03cH
	DB	03dH
	DB	03eH
	DB	03fH
	DB	040H
	DB	041H
	DB	042H
	DB	043H
	DB	044H
	DB	045H
	DB	046H
	DB	047H
	DB	048H
	DB	049H
	DB	04aH
	DB	04bH
	DB	04cH
	DB	04dH
	DB	04eH
	DB	04fH
	DB	050H
	DB	051H
	DB	052H
	DB	053H
	DB	054H
	DB	055H
	DB	056H
	DB	057H
	DB	058H
	DB	059H
	DB	05aH
	DB	05bH
	DB	05cH
	DB	05dH
	DB	05eH
	DB	05fH
	DB	060H
	DB	061H
	DB	062H
	DB	063H
	DB	064H
	DB	065H
	DB	066H
	DB	067H
	DB	068H
	DB	069H
	DB	06aH
	DB	06bH
	DB	06cH
	DB	06dH
	DB	06eH
	DB	06fH
	DB	070H
	DB	071H
	DB	072H
	DB	073H
	DB	074H
	DB	075H
	DB	076H
	DB	077H
	DB	078H
	DB	079H
	DB	07aH
	DB	07bH
	DB	07cH
	DB	07dH
	DB	07eH
	DB	07fH
	DB	0b6H
	DB	05dH
	DB	030H
	DB	03H
	DB	0cH
	DB	088H
	DB	0b4H
	DB	04cH
	DB	097H
	DB	05aH
	DB	034H
	DB	03fH
	DB	093H
	DB	0fbH
	DB	03cH
	DB	09H
	DB	061H
	DB	00H
	DB	066H
	DB	066H
	DB	01H
	DB	0cH
	DB	043H
	DB	037H
	DB	09eH
	DB	0deH
	DB	085H
	DB	04H
	DB	082H
	DB	013H
	DB	092H
	DB	01fH
	DB	0abH
	DB	098H
	DB	07dH
	DB	0a5H
	DB	0c8H
	DB	088H
	DB	0aH
	DB	0c6H
	DB	01cH
	DB	0e7H
	DB	0d1H
	DB	06H
	DB	090H
	DB	041H
	DB	0bbH
	DB	096H
	DB	0c5H
	DB	036H
	DB	084H
	DB	0daH
	DB	013H
	DB	0c6H
	DB	07eH
	DB	0e7H
	DB	0b7H
	DB	0cbH
	DB	068H
	DB	079H
	DB	05eH
	DB	0ecH
	DB	0acH
	DB	0e8H
	DB	076H
	DB	095H
	DB	0c5H
	DB	0abH
	DB	0e9H
	DB	06H
	DB	0dbH
	DB	0bbH
	DB	074H
	DB	04cH
	DB	0a0H
	DB	082H
	DB	06eH
	DB	060H
	DB	01dH
	DB	0ffH
	DB	0c9H
	DB	063H
	DB	047H
	DB	06H
	DB	0ffH
	DB	0e0H
	DB	044H
	DB	0b6H
	DB	071H
	DB	0e4H
	DB	0a5H
	DB	025H
	DB	04dH
	DB	0a2H
	DB	02eH
	DB	0bbH
	DB	044H
	DB	084H
	DB	0f1H
	DB	050H
	DB	086H
	DB	0beH
	DB	08H
	DB	081H
	DB	0abH
	DB	0f4H
	DB	033H
	DB	09eH
	DB	059H
	DB	035H
	DB	063H
	DB	0e2H
	DB	04aH
	DB	0dH
	DB	05fH
	DB	0f8H
	DB	0f3H
	DB	017H
	DB	0f1H
	DB	043H
	DB	01dH
	DB	08dH
	DB	06bH
	DB	016H
	DB	0eH
	DB	06bH
	DB	07eH
	DB	025H
	DD	020H
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	0ffH
	DB	00H
	DB	01H
	DB	02H
	DB	03H
	DB	04H
	DB	05H
	DB	06H
	DB	07H
	DB	08H
	DB	09H
	DB	0aH
	DB	0bH
	DB	0cH
	DB	0dH
	DB	0eH
	DB	0fH
	DB	010H
	DB	011H
	DB	012H
	DB	013H
	DB	014H
	DB	015H
	DB	016H
	DB	017H
	DB	018H
	DB	019H
	DB	01aH
	DB	01bH
	DB	01cH
	DB	01dH
	DB	01eH
	DB	01fH
	DB	020H
	DB	021H
	DB	022H
	DB	023H
	DB	024H
	DB	025H
	DB	026H
	DB	027H
	DB	028H
	DB	029H
	DB	02aH
	DB	02bH
	DB	02cH
	DB	02dH
	DB	02eH
	DB	02fH
	DB	030H
	DB	031H
	DB	032H
	DB	033H
	DB	034H
	DB	035H
	DB	036H
	DB	037H
	DB	038H
	DB	039H
	DB	03aH
	DB	03bH
	DB	03cH
	DB	03dH
	DB	03eH
	DB	03fH
	DB	040H
	DB	041H
	DB	042H
	DB	043H
	DB	044H
	DB	045H
	DB	046H
	DB	047H
	DB	048H
	DB	049H
	DB	04aH
	DB	04bH
	DB	04cH
	DB	04dH
	DB	04eH
	DB	04fH
	DB	050H
	DB	051H
	DB	052H
	DB	053H
	DB	054H
	DB	055H
	DB	056H
	DB	057H
	DB	058H
	DB	059H
	DB	05aH
	DB	05bH
	DB	05cH
	DB	05dH
	DB	05eH
	DB	05fH
	DB	060H
	DB	061H
	DB	062H
	DB	063H
	DB	064H
	DB	065H
	DB	066H
	DB	067H
	DB	068H
	DB	069H
	DB	06aH
	DB	06bH
	DB	06cH
	DB	06dH
	DB	06eH
	DB	06fH
	DB	070H
	DB	071H
	DB	072H
	DB	073H
	DB	074H
	DB	075H
	DB	076H
	DB	077H
	DB	078H
	DB	079H
	DB	07aH
	DB	07bH
	DB	07cH
	DB	07dH
	DB	07eH
	DB	07fH
	DB	0cdH
	DB	057H
	DB	01dH
	DB	0c3H
	DB	01eH
	DB	042H
	DB	095H
	DB	0a7H
	DB	0b5H
	DB	0c6H
	DB	024H
	DB	0d6H
	DB	05dH
	DB	091H
	DB	04bH
	DB	0b8H
	DB	03H
	DB	05bH
	DB	092H
	DB	098H
	DB	04dH
	DB	022H
	DB	0cH
	DB	098H
	DB	063H
	DB	0a0H
	DB	087H
	DB	0bcH
	DB	0b0H
	DB	04H
	DB	051H
	DB	07eH
	DB	09aH
	DB	03dH
	DB	0fbH
	DB	0eH
	DB	074H
	DB	0abH
	DB	0fH
	DB	0dfH
	DB	06cH
	DB	068H
	DB	064H
	DB	039H
	DB	0eH
	DB	022H
	DB	0afH
	DB	096H
	DB	050H
	DB	0a0H
	DB	0c4H
	DB	034H
	DB	05H
	DB	019H
	DB	0ceH
	DB	051H
	DB	089H
	DB	03aH
	DB	0f9H
	DB	0b1H
	DB	064H
	DB	086H
	DB	09fH
	DB	0f3H
	DB	0faH
	DB	01cH
	DB	0c8H
	DB	030H
	DB	064H
	DB	0f6H
	DB	04aH
	DB	05aH
	DB	04bH
	DB	04bH
	DB	095H
	DB	028H
	DB	04cH
	DB	04dH
	DB	089H
	DB	036H
	DB	066H
	DB	071H
	DB	025H
	DB	08dH
	DB	0c7H
	DB	0dbH
	DB	0a5H
	DB	093H
	DB	062H
	DB	06eH
	DB	03eH
	DB	07bH
	DB	081H
	DB	097H
	DB	0e9H
	DB	024H
	DB	016H
	DB	041H
	DB	03aH
	DB	0bdH
	DB	027H
	DB	07cH
	DB	06eH
	DB	0fH
	DB	08eH
	DB	062H
	DB	066H
	DB	0f9H
	DB	05eH
	DB	08dH
	DB	016H
	DB	04eH
	DB	0e3H
	DB	0a8H
	DB	03H
	DB	099H
	DB	0caH
	DB	06bH
	DB	02aH
	DB	058H
	DB	0faH
	DB	018H
	DB	0bfH
	DB	039H
	DB	079H
	DB	02H
	DB	07H
	DB	08aH
	DD	020H
	DB	00H
	DB	01H
	DB	02H
	DB	03H
	DB	04H
	DB	05H
	DB	06H
	DB	07H
	DB	08H
	DB	09H
	DB	0aH
	DB	0bH
	DB	0cH
	DB	0dH
	DB	0eH
	DB	0fH
	DB	010H
	DB	011H
	DB	012H
	DB	013H
	DB	014H
	DB	015H
	DB	016H
	DB	017H
	DB	018H
	DB	019H
	DB	01aH
	DB	01bH
	DB	01cH
	DB	01dH
	DB	01eH
	DB	01fH
	DB	00H
	DB	01H
	DB	02H
	DB	03H
	DB	04H
	DB	05H
	DB	06H
	DB	07H
	DB	08H
	DB	09H
	DB	0aH
	DB	0bH
	DB	0cH
	DB	0dH
	DB	0eH
	DB	0fH
	DB	010H
	DB	011H
	DB	012H
	DB	013H
	DB	014H
	DB	015H
	DB	016H
	DB	017H
	DB	018H
	DB	019H
	DB	01aH
	DB	01bH
	DB	01cH
	DB	01dH
	DB	01eH
	DB	01fH
	DB	020H
	DB	021H
	DB	022H
	DB	023H
	DB	024H
	DB	025H
	DB	026H
	DB	027H
	DB	028H
	DB	029H
	DB	02aH
	DB	02bH
	DB	02cH
	DB	02dH
	DB	02eH
	DB	02fH
	DB	030H
	DB	031H
	DB	032H
	DB	033H
	DB	034H
	DB	035H
	DB	036H
	DB	037H
	DB	038H
	DB	039H
	DB	03aH
	DB	03bH
	DB	03cH
	DB	03dH
	DB	03eH
	DB	03fH
	DB	040H
	DB	041H
	DB	042H
	DB	043H
	DB	044H
	DB	045H
	DB	046H
	DB	047H
	DB	048H
	DB	049H
	DB	04aH
	DB	04bH
	DB	04cH
	DB	04dH
	DB	04eH
	DB	04fH
	DB	050H
	DB	051H
	DB	052H
	DB	053H
	DB	054H
	DB	055H
	DB	056H
	DB	057H
	DB	058H
	DB	059H
	DB	05aH
	DB	05bH
	DB	05cH
	DB	05dH
	DB	05eH
	DB	05fH
	DB	060H
	DB	061H
	DB	062H
	DB	063H
	DB	064H
	DB	065H
	DB	066H
	DB	067H
	DB	068H
	DB	069H
	DB	06aH
	DB	06bH
	DB	06cH
	DB	06dH
	DB	06eH
	DB	06fH
	DB	070H
	DB	071H
	DB	072H
	DB	073H
	DB	074H
	DB	075H
	DB	076H
	DB	077H
	DB	078H
	DB	079H
	DB	07aH
	DB	07bH
	DB	07cH
	DB	07dH
	DB	07eH
	DB	07fH
	DB	05aH
	DB	06eH
	DB	04H
	DB	057H
	DB	08H
	DB	0fbH
	DB	071H
	DB	096H
	DB	0f0H
	DB	02eH
	DB	055H
	DB	03dH
	DB	02H
	DB	0c3H
	DB	0a6H
	DB	092H
	DB	0e9H
	DB	0c3H
	DB	0efH
	DB	08aH
	DB	0b2H
	DB	034H
	DB	053H
	DB	0e6H
	DB	0f0H
	DB	074H
	DB	09cH
	DB	0d6H
	DB	036H
	DB	0e7H
	DB	0a8H
	DB	08eH
	DB	061H
	DB	0a6H
	DB	093H
	DB	06eH
	DB	04eH
	DB	08fH
	DB	010H
	DB	01cH
	DB	01cH
	DB	0c1H
	DB	0f9H
	DB	093H
	DB	0b5H
	DB	042H
	DB	0a0H
	DB	0d4H
	DB	0e2H
	DB	074H
	DB	0eH
	DB	08aH
	DB	0faH
	DB	0d4H
	DB	0e4H
	DB	0d1H
	DB	05dH
	DB	0dH
	DB	066H
	DB	01bH
	DB	038H
	DB	02eH
	DB	0caH
	DB	089H
	DB	0a3H
	DB	07eH
	DB	0dfH
	DB	03fH
	DB	097H
	DB	05aH
	DB	0baH
	DB	0efH
	DB	093H
	DB	07bH
	DB	062H
	DB	0c7H
	DB	08dH
	DB	05bH
	DB	0b1H
	DB	057H
	DB	097H
	DB	04bH
	DB	041H
	DB	027H
	DB	038H
	DB	0e5H
	DB	0fH
	DB	045H
	DB	0c7H
	DB	0f9H
	DB	0dbH
	DB	025H
	DB	041H
	DB	03fH
	DB	027H
	DB	04bH
	DB	0d0H
	DB	0a2H
	DB	00H
	DB	0feH
	DB	0f4H
	DB	069H
	DB	024H
	DB	0a4H
	DB	0b8H
	DB	02dH
	DB	0ffH
	DB	0f8H
	DB	053H
	DB	08eH
	DB	0c1H
	DB	0b6H
	DB	0c7H
	DB	077H
	DB	0f1H
	DB	0a7H
	DB	055H
	DB	02dH
	DB	056H
	DB	07H
	DB	022H
	DB	0aeH
	DB	016H
	DB	05cH
	DB	04aH
	DB	05H
	DB	01eH
	DB	067H
_DATA	ENDS
PUBLIC	??_C@_01EEMJAFIK@?6?$AA@			; `string'
PUBLIC	??_C@_0BF@JNNODMCG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5fail?6?$AA@ ; `string'
PUBLIC	??_C@_0BF@GAIPIOBG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5pass?6?$AA@ ; `string'
PUBLIC	??_C@_0BA@JPOPBOHB@aes_encrypt_256?$AA@		; `string'
PUBLIC	??_C@_0BA@IEEAEIPL@aes_encrypt_196?$AA@		; `string'
PUBLIC	??_C@_0BA@BGJGIKJE@aes_encrypt_128?$AA@		; `string'
PUBLIC	??_C@_0BK@JMDGINJF@Info?3?5release?5old?5kernel?6?$AA@ ; `string'
PUBLIC	??_C@_0BC@GEOOPMIG@Test?3?5cl_encrypt?6?$AA@	; `string'
PUBLIC	__$ArrayPad$
PUBLIC	?cl_encrypt_test@@YAXXZ				; cl_encrypt_test
EXTRN	?cl_release_all@@YAXXZ:PROC			; cl_release_all
EXTRN	_memcmp:PROC
EXTRN	?cl_encrypt@@YAXPAEI0I@Z:PROC			; cl_encrypt
EXTRN	?key_schedule@@YAXPAEI@Z:PROC			; key_schedule
EXTRN	_memcpy:PROC
EXTRN	?cl_init@@YAXPADPAEII@Z:PROC			; cl_init
EXTRN	?cl_release_kernel@@YAXXZ:PROC			; cl_release_kernel
EXTRN	_printf:PROC
EXTRN	___security_cookie:DWORD
EXTRN	__RTC_CheckEsp:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT ??_C@_01EEMJAFIK@?6?$AA@
; File c:\users\tdrol\documents\visual studio 2010\projects\analizator\analizator-bd-opencl\cl_encrypt_test.cpp
CONST	SEGMENT
??_C@_01EEMJAFIK@?6?$AA@ DB 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@JNNODMCG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5fail?6?$AA@
CONST	SEGMENT
??_C@_0BF@JNNODMCG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5fail?6?$AA@ DB '  #'
	DB	'%i (%u bit) fail', 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@GAIPIOBG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5pass?6?$AA@
CONST	SEGMENT
??_C@_0BF@GAIPIOBG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5pass?6?$AA@ DB '  #'
	DB	'%i (%u bit) pass', 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@JPOPBOHB@aes_encrypt_256?$AA@
CONST	SEGMENT
??_C@_0BA@JPOPBOHB@aes_encrypt_256?$AA@ DB 'aes_encrypt_256', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@IEEAEIPL@aes_encrypt_196?$AA@
CONST	SEGMENT
??_C@_0BA@IEEAEIPL@aes_encrypt_196?$AA@ DB 'aes_encrypt_196', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@BGJGIKJE@aes_encrypt_128?$AA@
CONST	SEGMENT
??_C@_0BA@BGJGIKJE@aes_encrypt_128?$AA@ DB 'aes_encrypt_128', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@JMDGINJF@Info?3?5release?5old?5kernel?6?$AA@
CONST	SEGMENT
??_C@_0BK@JMDGINJF@Info?3?5release?5old?5kernel?6?$AA@ DB 'Info: release '
	DB	'old kernel', 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@GEOOPMIG@Test?3?5cl_encrypt?6?$AA@
CONST	SEGMENT
??_C@_0BC@GEOOPMIG@Test?3?5cl_encrypt?6?$AA@ DB 'Test: cl_encrypt', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT ?cl_encrypt_test@@YAXXZ
_TEXT	SEGMENT
tv73 = -620						; size = 4
_rk$6719 = -420						; size = 240
_data$6702 = -172					; size = 4
_i$6698 = -160						; size = 4
_last_kernel$ = -148					; size = 4
_result$ = -136						; size = 128
__$ArrayPad$ = -4					; size = 4
?cl_encrypt_test@@YAXXZ PROC				; cl_encrypt_test, COMDAT

; 194  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 620				; 0000026cH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-620]
	mov	ecx, 155				; 0000009bH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax

; 195  : 	printf("Test: cl_encrypt\n");

	push	OFFSET ??_C@_0BC@GEOOPMIG@Test?3?5cl_encrypt?6?$AA@
	call	_printf
	add	esp, 4

; 196  : 
; 197  : 	uint8_t result[DATA_LENGTH];
; 198  : 	int last_kernel = 0;

	mov	DWORD PTR _last_kernel$[ebp], 0

; 199  : 
; 200  : 	for (int i = 0; i < test_data_size; i++)

	mov	DWORD PTR _i$6698[ebp], 0
	jmp	SHORT $LN15@cl_encrypt
$LN14@cl_encrypt:
	mov	eax, DWORD PTR _i$6698[ebp]
	add	eax, 1
	mov	DWORD PTR _i$6698[ebp], eax
$LN15@cl_encrypt:
	mov	eax, DWORD PTR _i$6698[ebp]
	cmp	eax, DWORD PTR _test_data_size
	jge	$LN13@cl_encrypt

; 201  : 	{
; 202  : 		Encrypt_Data &data = test_data[i];

	mov	eax, DWORD PTR _i$6698[ebp]
	imul	eax, 292				; 00000124H
	add	eax, OFFSET ?test_data@@3PAUEncrypt_Data@@A ; test_data
	mov	DWORD PTR _data$6702[ebp], eax

; 203  : 		
; 204  : 		if (last_kernel == 0 || last_kernel != data.length)

	cmp	DWORD PTR _last_kernel$[ebp], 0
	je	SHORT $LN11@cl_encrypt
	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR _last_kernel$[ebp]
	cmp	ecx, DWORD PTR [eax]
	je	$LN12@cl_encrypt
$LN11@cl_encrypt:

; 205  : 		{
; 206  : 			if (last_kernel == 0)

	cmp	DWORD PTR _last_kernel$[ebp], 0
	jne	SHORT $LN10@cl_encrypt

; 207  : 			{
; 208  : 				last_kernel = data.length;

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _last_kernel$[ebp], ecx
	jmp	SHORT $LN9@cl_encrypt
$LN10@cl_encrypt:

; 209  : 			}
; 210  : 			else if (last_kernel != data.length)

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR _last_kernel$[ebp]
	cmp	ecx, DWORD PTR [eax]
	je	SHORT $LN9@cl_encrypt

; 211  : 			{
; 212  : 				cl_release_kernel();

	call	?cl_release_kernel@@YAXXZ		; cl_release_kernel

; 213  : 				printf("Info: release old kernel\n");

	push	OFFSET ??_C@_0BK@JMDGINJF@Info?3?5release?5old?5kernel?6?$AA@
	call	_printf
	add	esp, 4

; 214  : 				last_kernel = data.length;

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _last_kernel$[ebp], ecx
$LN9@cl_encrypt:

; 215  : 			}
; 216  : 
; 217  : 			switch (data.length)

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR tv73[ebp], ecx
	cmp	DWORD PTR tv73[ebp], 16			; 00000010H
	je	SHORT $LN5@cl_encrypt
	cmp	DWORD PTR tv73[ebp], 24			; 00000018H
	je	SHORT $LN4@cl_encrypt
	cmp	DWORD PTR tv73[ebp], 32			; 00000020H
	je	SHORT $LN3@cl_encrypt
	jmp	$LN12@cl_encrypt
$LN5@cl_encrypt:

; 218  : 			{
; 219  : 			case 16:
; 220  : 				cl_init("aes_encrypt_128", NULL, DATA_LENGTH, RKLENGTH(data.length));

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	eax, DWORD PTR [eax]
	cdq
	and	edx, 7
	add	eax, edx
	sar	eax, 3
	lea	ecx, DWORD PTR [eax*4+112]
	push	ecx
	push	128					; 00000080H
	push	0
	push	OFFSET ??_C@_0BA@BGJGIKJE@aes_encrypt_128?$AA@
	call	?cl_init@@YAXPADPAEII@Z			; cl_init
	add	esp, 16					; 00000010H

; 221  : 				break;

	jmp	SHORT $LN12@cl_encrypt
$LN4@cl_encrypt:

; 222  : 			case 24:
; 223  : 				cl_init("aes_encrypt_196", NULL, DATA_LENGTH, RKLENGTH(data.length));

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	eax, DWORD PTR [eax]
	cdq
	and	edx, 7
	add	eax, edx
	sar	eax, 3
	lea	ecx, DWORD PTR [eax*4+112]
	push	ecx
	push	128					; 00000080H
	push	0
	push	OFFSET ??_C@_0BA@IEEAEIPL@aes_encrypt_196?$AA@
	call	?cl_init@@YAXPADPAEII@Z			; cl_init
	add	esp, 16					; 00000010H

; 224  : 				break;

	jmp	SHORT $LN12@cl_encrypt
$LN3@cl_encrypt:

; 225  : 			case 32:
; 226  : 				cl_init("aes_encrypt_256", NULL, DATA_LENGTH, RKLENGTH(data.length));

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	eax, DWORD PTR [eax]
	cdq
	and	edx, 7
	add	eax, edx
	sar	eax, 3
	lea	ecx, DWORD PTR [eax*4+112]
	push	ecx
	push	128					; 00000080H
	push	0
	push	OFFSET ??_C@_0BA@JPOPBOHB@aes_encrypt_256?$AA@
	call	?cl_init@@YAXPADPAEII@Z			; cl_init
	add	esp, 16					; 00000010H
$LN12@cl_encrypt:

; 227  : 				break;
; 228  : 			}
; 229  : 		}
; 230  : 
; 231  : 		
; 232  : 		uint8_t rk[RKLENGTH(256)];
; 233  : 
; 234  : 		memcpy(rk, data.key, data.length);

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _data$6702[ebp]
	add	edx, 4
	push	edx
	lea	eax, DWORD PTR _rk$6719[ebp]
	push	eax
	call	_memcpy
	add	esp, 12					; 0000000cH

; 235  : 
; 236  : 		key_schedule(rk, data.length*8);

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR [eax]
	shl	ecx, 3
	push	ecx
	lea	edx, DWORD PTR _rk$6719[ebp]
	push	edx
	call	?key_schedule@@YAXPAEI@Z		; key_schedule
	add	esp, 8

; 237  : 
; 238  : 		memcpy(result, data.plaintext, DATA_LENGTH);

	push	128					; 00000080H
	mov	eax, DWORD PTR _data$6702[ebp]
	add	eax, 36					; 00000024H
	push	eax
	lea	ecx, DWORD PTR _result$[ebp]
	push	ecx
	call	_memcpy
	add	esp, 12					; 0000000cH

; 239  : 
; 240  : 		cl_encrypt(rk, data.length, result, DATA_LENGTH);

	push	128					; 00000080H
	lea	eax, DWORD PTR _result$[ebp]
	push	eax
	mov	ecx, DWORD PTR _data$6702[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	lea	eax, DWORD PTR _rk$6719[ebp]
	push	eax
	call	?cl_encrypt@@YAXPAEI0I@Z		; cl_encrypt
	add	esp, 16					; 00000010H

; 241  : 
; 242  : 		if (memcmp(result, data.ciphertext, DATA_LENGTH) == 0)

	push	128					; 00000080H
	mov	eax, DWORD PTR _data$6702[ebp]
	add	eax, 164				; 000000a4H
	push	eax
	lea	ecx, DWORD PTR _result$[ebp]
	push	ecx
	call	_memcmp
	add	esp, 12					; 0000000cH
	test	eax, eax
	jne	SHORT $LN2@cl_encrypt

; 243  : 		{
; 244  : 			printf("  #%i (%u bit) pass\n", i+1, data.length);

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _i$6698[ebp]
	add	edx, 1
	push	edx
	push	OFFSET ??_C@_0BF@GAIPIOBG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5pass?6?$AA@
	call	_printf
	add	esp, 12					; 0000000cH

; 245  : 		}
; 246  : 		else

	jmp	SHORT $LN1@cl_encrypt
$LN2@cl_encrypt:

; 247  : 		{
; 248  : 			printf("  #%i (%u bit) fail\n", i+1, data.length);

	mov	eax, DWORD PTR _data$6702[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _i$6698[ebp]
	add	edx, 1
	push	edx
	push	OFFSET ??_C@_0BF@JNNODMCG@?5?5?$CD?$CFi?5?$CI?$CFu?5bit?$CJ?5fail?6?$AA@
	call	_printf
	add	esp, 12					; 0000000cH
$LN1@cl_encrypt:

; 249  : 		}
; 250  : 	}

	jmp	$LN14@cl_encrypt
$LN13@cl_encrypt:

; 251  : 
; 252  : 	cl_release_all();

	call	?cl_release_all@@YAXXZ			; cl_release_all

; 253  : 
; 254  : 	printf("\n");

	push	OFFSET ??_C@_01EEMJAFIK@?6?$AA@
	call	_printf
	add	esp, 4

; 255  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN21@cl_encrypt
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 620				; 0000026cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN21@cl_encrypt:
	DD	2
	DD	$LN20@cl_encrypt
$LN20@cl_encrypt:
	DD	-136					; ffffff78H
	DD	128					; 00000080H
	DD	$LN18@cl_encrypt
	DD	-420					; fffffe5cH
	DD	240					; 000000f0H
	DD	$LN19@cl_encrypt
$LN19@cl_encrypt:
	DB	114					; 00000072H
	DB	107					; 0000006bH
	DB	0
$LN18@cl_encrypt:
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	115					; 00000073H
	DB	117					; 00000075H
	DB	108					; 0000006cH
	DB	116					; 00000074H
	DB	0
?cl_encrypt_test@@YAXXZ ENDP				; cl_encrypt_test
_TEXT	ENDS
END
